// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/account-middleware/pkg/db/ent/limitation"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LimitationCreate is the builder for creating a Limitation entity.
type LimitationCreate struct {
	config
	mutation *LimitationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (lc *LimitationCreate) SetCreatedAt(u uint32) *LimitationCreate {
	lc.mutation.SetCreatedAt(u)
	return lc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lc *LimitationCreate) SetNillableCreatedAt(u *uint32) *LimitationCreate {
	if u != nil {
		lc.SetCreatedAt(*u)
	}
	return lc
}

// SetUpdatedAt sets the "updated_at" field.
func (lc *LimitationCreate) SetUpdatedAt(u uint32) *LimitationCreate {
	lc.mutation.SetUpdatedAt(u)
	return lc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (lc *LimitationCreate) SetNillableUpdatedAt(u *uint32) *LimitationCreate {
	if u != nil {
		lc.SetUpdatedAt(*u)
	}
	return lc
}

// SetDeletedAt sets the "deleted_at" field.
func (lc *LimitationCreate) SetDeletedAt(u uint32) *LimitationCreate {
	lc.mutation.SetDeletedAt(u)
	return lc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (lc *LimitationCreate) SetNillableDeletedAt(u *uint32) *LimitationCreate {
	if u != nil {
		lc.SetDeletedAt(*u)
	}
	return lc
}

// SetCoinTypeID sets the "coin_type_id" field.
func (lc *LimitationCreate) SetCoinTypeID(u uuid.UUID) *LimitationCreate {
	lc.mutation.SetCoinTypeID(u)
	return lc
}

// SetNillableCoinTypeID sets the "coin_type_id" field if the given value is not nil.
func (lc *LimitationCreate) SetNillableCoinTypeID(u *uuid.UUID) *LimitationCreate {
	if u != nil {
		lc.SetCoinTypeID(*u)
	}
	return lc
}

// SetLimitation sets the "limitation" field.
func (lc *LimitationCreate) SetLimitation(s string) *LimitationCreate {
	lc.mutation.SetLimitation(s)
	return lc
}

// SetNillableLimitation sets the "limitation" field if the given value is not nil.
func (lc *LimitationCreate) SetNillableLimitation(s *string) *LimitationCreate {
	if s != nil {
		lc.SetLimitation(*s)
	}
	return lc
}

// SetAmount sets the "amount" field.
func (lc *LimitationCreate) SetAmount(d decimal.Decimal) *LimitationCreate {
	lc.mutation.SetAmount(d)
	return lc
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (lc *LimitationCreate) SetNillableAmount(d *decimal.Decimal) *LimitationCreate {
	if d != nil {
		lc.SetAmount(*d)
	}
	return lc
}

// SetID sets the "id" field.
func (lc *LimitationCreate) SetID(u uuid.UUID) *LimitationCreate {
	lc.mutation.SetID(u)
	return lc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (lc *LimitationCreate) SetNillableID(u *uuid.UUID) *LimitationCreate {
	if u != nil {
		lc.SetID(*u)
	}
	return lc
}

// Mutation returns the LimitationMutation object of the builder.
func (lc *LimitationCreate) Mutation() *LimitationMutation {
	return lc.mutation
}

// Save creates the Limitation in the database.
func (lc *LimitationCreate) Save(ctx context.Context) (*Limitation, error) {
	var (
		err  error
		node *Limitation
	)
	if err := lc.defaults(); err != nil {
		return nil, err
	}
	if len(lc.hooks) == 0 {
		if err = lc.check(); err != nil {
			return nil, err
		}
		node, err = lc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LimitationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = lc.check(); err != nil {
				return nil, err
			}
			lc.mutation = mutation
			if node, err = lc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(lc.hooks) - 1; i >= 0; i-- {
			if lc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, lc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Limitation)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from LimitationMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LimitationCreate) SaveX(ctx context.Context) *Limitation {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LimitationCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LimitationCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *LimitationCreate) defaults() error {
	if _, ok := lc.mutation.CreatedAt(); !ok {
		if limitation.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized limitation.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := limitation.DefaultCreatedAt()
		lc.mutation.SetCreatedAt(v)
	}
	if _, ok := lc.mutation.UpdatedAt(); !ok {
		if limitation.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized limitation.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := limitation.DefaultUpdatedAt()
		lc.mutation.SetUpdatedAt(v)
	}
	if _, ok := lc.mutation.DeletedAt(); !ok {
		if limitation.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized limitation.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := limitation.DefaultDeletedAt()
		lc.mutation.SetDeletedAt(v)
	}
	if _, ok := lc.mutation.CoinTypeID(); !ok {
		if limitation.DefaultCoinTypeID == nil {
			return fmt.Errorf("ent: uninitialized limitation.DefaultCoinTypeID (forgotten import ent/runtime?)")
		}
		v := limitation.DefaultCoinTypeID()
		lc.mutation.SetCoinTypeID(v)
	}
	if _, ok := lc.mutation.Limitation(); !ok {
		v := limitation.DefaultLimitation
		lc.mutation.SetLimitation(v)
	}
	if _, ok := lc.mutation.Amount(); !ok {
		v := limitation.DefaultAmount
		lc.mutation.SetAmount(v)
	}
	if _, ok := lc.mutation.ID(); !ok {
		if limitation.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized limitation.DefaultID (forgotten import ent/runtime?)")
		}
		v := limitation.DefaultID()
		lc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (lc *LimitationCreate) check() error {
	if _, ok := lc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Limitation.created_at"`)}
	}
	if _, ok := lc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Limitation.updated_at"`)}
	}
	if _, ok := lc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Limitation.deleted_at"`)}
	}
	return nil
}

func (lc *LimitationCreate) sqlSave(ctx context.Context) (*Limitation, error) {
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (lc *LimitationCreate) createSpec() (*Limitation, *sqlgraph.CreateSpec) {
	var (
		_node = &Limitation{config: lc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: limitation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: limitation.FieldID,
			},
		}
	)
	_spec.OnConflict = lc.conflict
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := lc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: limitation.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := lc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: limitation.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := lc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: limitation.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := lc.mutation.CoinTypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: limitation.FieldCoinTypeID,
		})
		_node.CoinTypeID = value
	}
	if value, ok := lc.mutation.Limitation(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: limitation.FieldLimitation,
		})
		_node.Limitation = value
	}
	if value, ok := lc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: limitation.FieldAmount,
		})
		_node.Amount = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Limitation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LimitationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (lc *LimitationCreate) OnConflict(opts ...sql.ConflictOption) *LimitationUpsertOne {
	lc.conflict = opts
	return &LimitationUpsertOne{
		create: lc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Limitation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (lc *LimitationCreate) OnConflictColumns(columns ...string) *LimitationUpsertOne {
	lc.conflict = append(lc.conflict, sql.ConflictColumns(columns...))
	return &LimitationUpsertOne{
		create: lc,
	}
}

type (
	// LimitationUpsertOne is the builder for "upsert"-ing
	//  one Limitation node.
	LimitationUpsertOne struct {
		create *LimitationCreate
	}

	// LimitationUpsert is the "OnConflict" setter.
	LimitationUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *LimitationUpsert) SetCreatedAt(v uint32) *LimitationUpsert {
	u.Set(limitation.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LimitationUpsert) UpdateCreatedAt() *LimitationUpsert {
	u.SetExcluded(limitation.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *LimitationUpsert) AddCreatedAt(v uint32) *LimitationUpsert {
	u.Add(limitation.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LimitationUpsert) SetUpdatedAt(v uint32) *LimitationUpsert {
	u.Set(limitation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LimitationUpsert) UpdateUpdatedAt() *LimitationUpsert {
	u.SetExcluded(limitation.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *LimitationUpsert) AddUpdatedAt(v uint32) *LimitationUpsert {
	u.Add(limitation.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LimitationUpsert) SetDeletedAt(v uint32) *LimitationUpsert {
	u.Set(limitation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LimitationUpsert) UpdateDeletedAt() *LimitationUpsert {
	u.SetExcluded(limitation.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *LimitationUpsert) AddDeletedAt(v uint32) *LimitationUpsert {
	u.Add(limitation.FieldDeletedAt, v)
	return u
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *LimitationUpsert) SetCoinTypeID(v uuid.UUID) *LimitationUpsert {
	u.Set(limitation.FieldCoinTypeID, v)
	return u
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *LimitationUpsert) UpdateCoinTypeID() *LimitationUpsert {
	u.SetExcluded(limitation.FieldCoinTypeID)
	return u
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *LimitationUpsert) ClearCoinTypeID() *LimitationUpsert {
	u.SetNull(limitation.FieldCoinTypeID)
	return u
}

// SetLimitation sets the "limitation" field.
func (u *LimitationUpsert) SetLimitation(v string) *LimitationUpsert {
	u.Set(limitation.FieldLimitation, v)
	return u
}

// UpdateLimitation sets the "limitation" field to the value that was provided on create.
func (u *LimitationUpsert) UpdateLimitation() *LimitationUpsert {
	u.SetExcluded(limitation.FieldLimitation)
	return u
}

// ClearLimitation clears the value of the "limitation" field.
func (u *LimitationUpsert) ClearLimitation() *LimitationUpsert {
	u.SetNull(limitation.FieldLimitation)
	return u
}

// SetAmount sets the "amount" field.
func (u *LimitationUpsert) SetAmount(v decimal.Decimal) *LimitationUpsert {
	u.Set(limitation.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LimitationUpsert) UpdateAmount() *LimitationUpsert {
	u.SetExcluded(limitation.FieldAmount)
	return u
}

// ClearAmount clears the value of the "amount" field.
func (u *LimitationUpsert) ClearAmount() *LimitationUpsert {
	u.SetNull(limitation.FieldAmount)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Limitation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(limitation.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *LimitationUpsertOne) UpdateNewValues() *LimitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(limitation.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Limitation.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *LimitationUpsertOne) Ignore() *LimitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LimitationUpsertOne) DoNothing() *LimitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LimitationCreate.OnConflict
// documentation for more info.
func (u *LimitationUpsertOne) Update(set func(*LimitationUpsert)) *LimitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LimitationUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LimitationUpsertOne) SetCreatedAt(v uint32) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *LimitationUpsertOne) AddCreatedAt(v uint32) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LimitationUpsertOne) UpdateCreatedAt() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LimitationUpsertOne) SetUpdatedAt(v uint32) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *LimitationUpsertOne) AddUpdatedAt(v uint32) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LimitationUpsertOne) UpdateUpdatedAt() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LimitationUpsertOne) SetDeletedAt(v uint32) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *LimitationUpsertOne) AddDeletedAt(v uint32) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LimitationUpsertOne) UpdateDeletedAt() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *LimitationUpsertOne) SetCoinTypeID(v uuid.UUID) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *LimitationUpsertOne) UpdateCoinTypeID() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *LimitationUpsertOne) ClearCoinTypeID() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetLimitation sets the "limitation" field.
func (u *LimitationUpsertOne) SetLimitation(v string) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.SetLimitation(v)
	})
}

// UpdateLimitation sets the "limitation" field to the value that was provided on create.
func (u *LimitationUpsertOne) UpdateLimitation() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateLimitation()
	})
}

// ClearLimitation clears the value of the "limitation" field.
func (u *LimitationUpsertOne) ClearLimitation() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.ClearLimitation()
	})
}

// SetAmount sets the "amount" field.
func (u *LimitationUpsertOne) SetAmount(v decimal.Decimal) *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.SetAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LimitationUpsertOne) UpdateAmount() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *LimitationUpsertOne) ClearAmount() *LimitationUpsertOne {
	return u.Update(func(s *LimitationUpsert) {
		s.ClearAmount()
	})
}

// Exec executes the query.
func (u *LimitationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LimitationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LimitationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LimitationUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: LimitationUpsertOne.ID is not supported by MySQL driver. Use LimitationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LimitationUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LimitationCreateBulk is the builder for creating many Limitation entities in bulk.
type LimitationCreateBulk struct {
	config
	builders []*LimitationCreate
	conflict []sql.ConflictOption
}

// Save creates the Limitation entities in the database.
func (lcb *LimitationCreateBulk) Save(ctx context.Context) ([]*Limitation, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Limitation, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LimitationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = lcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LimitationCreateBulk) SaveX(ctx context.Context) []*Limitation {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LimitationCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LimitationCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Limitation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LimitationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (lcb *LimitationCreateBulk) OnConflict(opts ...sql.ConflictOption) *LimitationUpsertBulk {
	lcb.conflict = opts
	return &LimitationUpsertBulk{
		create: lcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Limitation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (lcb *LimitationCreateBulk) OnConflictColumns(columns ...string) *LimitationUpsertBulk {
	lcb.conflict = append(lcb.conflict, sql.ConflictColumns(columns...))
	return &LimitationUpsertBulk{
		create: lcb,
	}
}

// LimitationUpsertBulk is the builder for "upsert"-ing
// a bulk of Limitation nodes.
type LimitationUpsertBulk struct {
	create *LimitationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Limitation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(limitation.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *LimitationUpsertBulk) UpdateNewValues() *LimitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(limitation.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Limitation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *LimitationUpsertBulk) Ignore() *LimitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LimitationUpsertBulk) DoNothing() *LimitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LimitationCreateBulk.OnConflict
// documentation for more info.
func (u *LimitationUpsertBulk) Update(set func(*LimitationUpsert)) *LimitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LimitationUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LimitationUpsertBulk) SetCreatedAt(v uint32) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *LimitationUpsertBulk) AddCreatedAt(v uint32) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LimitationUpsertBulk) UpdateCreatedAt() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LimitationUpsertBulk) SetUpdatedAt(v uint32) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *LimitationUpsertBulk) AddUpdatedAt(v uint32) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LimitationUpsertBulk) UpdateUpdatedAt() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LimitationUpsertBulk) SetDeletedAt(v uint32) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *LimitationUpsertBulk) AddDeletedAt(v uint32) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LimitationUpsertBulk) UpdateDeletedAt() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *LimitationUpsertBulk) SetCoinTypeID(v uuid.UUID) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *LimitationUpsertBulk) UpdateCoinTypeID() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *LimitationUpsertBulk) ClearCoinTypeID() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetLimitation sets the "limitation" field.
func (u *LimitationUpsertBulk) SetLimitation(v string) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.SetLimitation(v)
	})
}

// UpdateLimitation sets the "limitation" field to the value that was provided on create.
func (u *LimitationUpsertBulk) UpdateLimitation() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateLimitation()
	})
}

// ClearLimitation clears the value of the "limitation" field.
func (u *LimitationUpsertBulk) ClearLimitation() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.ClearLimitation()
	})
}

// SetAmount sets the "amount" field.
func (u *LimitationUpsertBulk) SetAmount(v decimal.Decimal) *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.SetAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *LimitationUpsertBulk) UpdateAmount() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *LimitationUpsertBulk) ClearAmount() *LimitationUpsertBulk {
	return u.Update(func(s *LimitationUpsert) {
		s.ClearAmount()
	})
}

// Exec executes the query.
func (u *LimitationUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LimitationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LimitationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LimitationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
