// Code generated by ent, DO NOT EDIT.

package deposit

import (
	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/account-middleware/pkg/db/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAppID), v))
	})
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAccountID), v))
	})
}

// Incoming applies equality check predicate on the "incoming" field. It's identical to IncomingEQ.
func Incoming(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIncoming), v))
	})
}

// Outcoming applies equality check predicate on the "outcoming" field. It's identical to OutcomingEQ.
func Outcoming(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOutcoming), v))
	})
}

// CollectingTid applies equality check predicate on the "collecting_tid" field. It's identical to CollectingTidEQ.
func CollectingTid(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCollectingTid), v))
	})
}

// ScannableAt applies equality check predicate on the "scannable_at" field. It's identical to ScannableAtEQ.
func ScannableAt(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldScannableAt), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...uint32) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...uint32) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...uint32) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...uint32) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...uint32) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...uint32) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeletedAt), v))
	})
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAppID), v))
	})
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAppID), v))
	})
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...uuid.UUID) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldAppID), v...))
	})
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...uuid.UUID) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldAppID), v...))
	})
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAppID), v))
	})
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAppID), v))
	})
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAppID), v))
	})
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAppID), v))
	})
}

// AppIDIsNil applies the IsNil predicate on the "app_id" field.
func AppIDIsNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldAppID)))
	})
}

// AppIDNotNil applies the NotNil predicate on the "app_id" field.
func AppIDNotNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldAppID)))
	})
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserID), v))
	})
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUserID), v...))
	})
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUserID), v...))
	})
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUserID), v))
	})
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUserID), v))
	})
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUserID), v))
	})
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUserID), v))
	})
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldUserID)))
	})
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldUserID)))
	})
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAccountID), v))
	})
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAccountID), v))
	})
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...uuid.UUID) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldAccountID), v...))
	})
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...uuid.UUID) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldAccountID), v...))
	})
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAccountID), v))
	})
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAccountID), v))
	})
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAccountID), v))
	})
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAccountID), v))
	})
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldAccountID)))
	})
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldAccountID)))
	})
}

// IncomingEQ applies the EQ predicate on the "incoming" field.
func IncomingEQ(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIncoming), v))
	})
}

// IncomingNEQ applies the NEQ predicate on the "incoming" field.
func IncomingNEQ(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIncoming), v))
	})
}

// IncomingIn applies the In predicate on the "incoming" field.
func IncomingIn(vs ...decimal.Decimal) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldIncoming), v...))
	})
}

// IncomingNotIn applies the NotIn predicate on the "incoming" field.
func IncomingNotIn(vs ...decimal.Decimal) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldIncoming), v...))
	})
}

// IncomingGT applies the GT predicate on the "incoming" field.
func IncomingGT(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIncoming), v))
	})
}

// IncomingGTE applies the GTE predicate on the "incoming" field.
func IncomingGTE(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIncoming), v))
	})
}

// IncomingLT applies the LT predicate on the "incoming" field.
func IncomingLT(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIncoming), v))
	})
}

// IncomingLTE applies the LTE predicate on the "incoming" field.
func IncomingLTE(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIncoming), v))
	})
}

// IncomingIsNil applies the IsNil predicate on the "incoming" field.
func IncomingIsNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldIncoming)))
	})
}

// IncomingNotNil applies the NotNil predicate on the "incoming" field.
func IncomingNotNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldIncoming)))
	})
}

// OutcomingEQ applies the EQ predicate on the "outcoming" field.
func OutcomingEQ(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOutcoming), v))
	})
}

// OutcomingNEQ applies the NEQ predicate on the "outcoming" field.
func OutcomingNEQ(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOutcoming), v))
	})
}

// OutcomingIn applies the In predicate on the "outcoming" field.
func OutcomingIn(vs ...decimal.Decimal) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldOutcoming), v...))
	})
}

// OutcomingNotIn applies the NotIn predicate on the "outcoming" field.
func OutcomingNotIn(vs ...decimal.Decimal) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldOutcoming), v...))
	})
}

// OutcomingGT applies the GT predicate on the "outcoming" field.
func OutcomingGT(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOutcoming), v))
	})
}

// OutcomingGTE applies the GTE predicate on the "outcoming" field.
func OutcomingGTE(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOutcoming), v))
	})
}

// OutcomingLT applies the LT predicate on the "outcoming" field.
func OutcomingLT(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOutcoming), v))
	})
}

// OutcomingLTE applies the LTE predicate on the "outcoming" field.
func OutcomingLTE(v decimal.Decimal) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOutcoming), v))
	})
}

// OutcomingIsNil applies the IsNil predicate on the "outcoming" field.
func OutcomingIsNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldOutcoming)))
	})
}

// OutcomingNotNil applies the NotNil predicate on the "outcoming" field.
func OutcomingNotNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldOutcoming)))
	})
}

// CollectingTidEQ applies the EQ predicate on the "collecting_tid" field.
func CollectingTidEQ(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCollectingTid), v))
	})
}

// CollectingTidNEQ applies the NEQ predicate on the "collecting_tid" field.
func CollectingTidNEQ(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCollectingTid), v))
	})
}

// CollectingTidIn applies the In predicate on the "collecting_tid" field.
func CollectingTidIn(vs ...uuid.UUID) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCollectingTid), v...))
	})
}

// CollectingTidNotIn applies the NotIn predicate on the "collecting_tid" field.
func CollectingTidNotIn(vs ...uuid.UUID) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCollectingTid), v...))
	})
}

// CollectingTidGT applies the GT predicate on the "collecting_tid" field.
func CollectingTidGT(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCollectingTid), v))
	})
}

// CollectingTidGTE applies the GTE predicate on the "collecting_tid" field.
func CollectingTidGTE(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCollectingTid), v))
	})
}

// CollectingTidLT applies the LT predicate on the "collecting_tid" field.
func CollectingTidLT(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCollectingTid), v))
	})
}

// CollectingTidLTE applies the LTE predicate on the "collecting_tid" field.
func CollectingTidLTE(v uuid.UUID) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCollectingTid), v))
	})
}

// CollectingTidIsNil applies the IsNil predicate on the "collecting_tid" field.
func CollectingTidIsNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldCollectingTid)))
	})
}

// CollectingTidNotNil applies the NotNil predicate on the "collecting_tid" field.
func CollectingTidNotNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldCollectingTid)))
	})
}

// ScannableAtEQ applies the EQ predicate on the "scannable_at" field.
func ScannableAtEQ(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldScannableAt), v))
	})
}

// ScannableAtNEQ applies the NEQ predicate on the "scannable_at" field.
func ScannableAtNEQ(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldScannableAt), v))
	})
}

// ScannableAtIn applies the In predicate on the "scannable_at" field.
func ScannableAtIn(vs ...uint32) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldScannableAt), v...))
	})
}

// ScannableAtNotIn applies the NotIn predicate on the "scannable_at" field.
func ScannableAtNotIn(vs ...uint32) predicate.Deposit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldScannableAt), v...))
	})
}

// ScannableAtGT applies the GT predicate on the "scannable_at" field.
func ScannableAtGT(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldScannableAt), v))
	})
}

// ScannableAtGTE applies the GTE predicate on the "scannable_at" field.
func ScannableAtGTE(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldScannableAt), v))
	})
}

// ScannableAtLT applies the LT predicate on the "scannable_at" field.
func ScannableAtLT(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldScannableAt), v))
	})
}

// ScannableAtLTE applies the LTE predicate on the "scannable_at" field.
func ScannableAtLTE(v uint32) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldScannableAt), v))
	})
}

// ScannableAtIsNil applies the IsNil predicate on the "scannable_at" field.
func ScannableAtIsNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldScannableAt)))
	})
}

// ScannableAtNotNil applies the NotNil predicate on the "scannable_at" field.
func ScannableAtNotNil() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldScannableAt)))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		p(s.Not())
	})
}
